### ISSUE TITLE
Running project locally

### ISSUE THREAD

**Issue by anurag-dhamala** [fiberplane/fp#224]
It required nightly version of rust to build the project locally. 

It'd be nice to mention in README.md or CONTRIBUTING.md to use nightly version of rust.

We can switch to nightly version easily if rust is installed via rustup: 
` rustup default nightly`

To switch back to stable version, we can do: 
`rustup default stable`

**Comment by keturiosakys** [comment]
Hi @anurag-dhamala, just confirmed with the team - the project builds with the stable version of Rust. Closing this issue
